### ISSUE TITLE
Transmission logic is faulty

### ISSUE THREAD

**Issue by KevinMcCarthyAtIDM** [InstituteforDiseaseModeling/laser-measles#4]
In `transmission.py`, line 134:
`if (force > 0) and (np.random.random_sample() < force):`

is incorrect logic.  Force is a rate parameter here, which is allowed to be >1 but that does not imply immediate infection of every individual.  The correct logic is:

`if (force > 0) and (np.random.random_sample() < (1-np.exp(-force))):`

Which converts the rate "force" into a probability of a state transition in a unit timestep.  

Note that eventually, if we want to allow certain steps in the model to increment by more than 1 tick for efficiency, the relevant term would be `(1-np.exp(-force * time_step))`.  We're not doing that right now, but something to come back to?

**Comment by KevinMcCarthyAtIDM** [comment]
For efficiency, it may make more sense to convert all of the forces to probabilities outside of the number step, so that it can be done all at once per patch, rather than for each individual.  So that would look something like:
`forces = 1-np.exp(-1*forces)`

Following the conventions in the code (maybe because we are operating on a view?), I think that's
`np.exp(-forces, out=forces)`
`np.subtract(1, forces, out=forces)`

**Comment by krosenfeld-IDM** [comment]
Can use `np.expm1`:

https://github.com/InstituteforDiseaseModeling/laser-generic/blob/45090ba851994eb2fd97541e612459c5e379b2c6/src/laser_generic/transmission.py#L118-L119

**Comment by krosenfeld-IDM** [comment]
In practice the force of infection should be quite small (<<1) which - this came up before when investigating the use of Poisson draws to calculate the number of infections [teams link](https://teams.microsoft.com/l/message/19:meeting_NjdiNDAyMDYtODI3Yi00ZjUxLTk1ZmMtYmYxMDAwOWE3ZTdk@thread.v2/1707784548154?context=%7B%22contextType%22%3A%22chat%22%7D). A brief look at run-time performance in both `laser-measles` and `laser-generic` I don't see a difference in run-time so seems like a good choice to use the full expression.

**Comment by KevinMcCarthyAtIDM** [comment]
I did a little test on my code space and thought expm1 is slightly faster, but not convinced it was much of a bottleneck.  
You’re right that most of the time the force of infection is small so 1-exp(-X) ~ x, but not always - SI type models go to large infected fractions easily, and during outbreaks of high transmissibility diseases I think it’s plausible to get into the FOI >0.1 range where that approximation gets bad.

**Comment by clorton** [comment]
It looks like the correct code, using `expm1()` is:

```python
forces *= -1 # forces = -forces
np.expm1(forces, out=forces) # forces = e^(-forces) - 1
forces *= -1 # forces = 1 - e^(-forces)
```

We want $1 -e^{-forces}$ but `expm1()` calculates $e^x-1$.
So we need `-expm1()` ($1-e^x$) and $x = -\text {forces}$.

@KevinMcCarthyAtIDM @krosenfeld-IDM

**Comment by krosenfeld-IDM** [comment]
Sorry if I'm missing something but isn't that what we had @clorton? Just with the first `np.negative(force, out=force)` part of the original `np.expm1` expression:
https://github.com/InstituteforDiseaseModeling/laser-measles/blob/3018f11cf9d8f09a183de7adce9d392c94926576/src/laser_measles/transmission.py#L106

Maybe there is something different in the performance? Relatedly, `np.expm1(x)` has better prevision than `np.exp` for small values of `x`, but we are losing out on code clarity.

**Comment by clorton** [comment]
It's not clear to me if `-forces` is in place or makes a copy. The goal is to prevent copies. If `-forces` does _not_ make a copy, then all is good.

**Comment by krosenfeld-IDM** [comment]
got it - I think you're right that `-forces` is not an in place operation. good catch! The changes you suggest look good to me.
